apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: inventory-system
type: Opaque
data:
  JWT_SECRET: BASE64_ENCODED_VALUE_HERE
  
# Instructions:
# 1. Replace BASE64_ENCODED_VALUE_HERE with base64-encoded values.
#    Example:
#    echo -n "your_jwt_secret" | base64
#
# 2. Save this file as auth-secret.yaml (DO NOT COMMIT IT).
#
# 3. Copy the file to the kubernetes folder. Proceed to next step in the README.
