name: Build Auth Service

on:
  push:
    paths:
      - "backend/authentification-service/**"
      - ".github/workflows/auth-service.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/authentification-service/**"
      - ".github/workflows/auth-service.yml"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Auth Service Docker Image
        run: |
          docker build --target production -t auth-service:latest ./backend/authentification-service
