name: Test Kubernetes Manifests

on:
  - pull_request

jobs:
  test-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@v0.0.19
        with:
          driver: docker

      - name: Create Kubernetes Secret File
        run: |
          cat <<EOF > kubernetes/postgres-secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-secret
            namespace: inventory-system
          type: Opaque
          data:
            POSTGRES_DB: $(echo -n "${{ secrets.POSTGRES_DB }}" | base64)
            POSTGRES_USER: $(echo -n "${{ secrets.POSTGRES_USER }}" | base64)
            POSTGRES_PASSWORD: $(echo -n "${{ secrets.POSTGRES_PASSWORD }}" | base64)
          EOF
          cat <<EOF > kubernetes/auth-secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: auth-secret
            namespace: inventory-system
          type: Opaque
          data:
            JWT_SECRET: $(echo -n "${{ secrets.JWT_SECRET }}" | base64)
          EOF

      - name: Validate Kubernetes Manifests (Dry Run)
        run: |
          kubectl apply --dry-run=client -f kubernetes/

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/
          sleep 30

      - name: Check for Failed Pods
        run: |
          kubectl get pods -n inventory-system
          if kubectl get pods -A | grep -q 'CrashLoopBackOff\|Error\|ImagePullBackOff'; then
            echo "Some pods failed to start!"
            exit 1
          fi

      - name: Wait for Pods to be Ready
        run: |
          kubectl wait --for=condition=Ready pod --all -A --timeout=60s
