name: Build Product Service

on:
  push:
    paths:
      - "backend/product-service/**"
      - ".github/workflows/product-service.yml"
  pull_request:
    branches:
      - main
    paths:
      - "backend/product-service/**"
      - ".github/workflows/product-service.yml"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Product Service Docker Image
        run: |
          docker build --target production -t product-service:latest ./backend/product-service
